version: '3.8'

services:
  php:
    build: .
    container_name: php_web
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql_db
    volumes:
      - ./db:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=senha123
      - MYSQL_DATABASE=demo
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8002:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=senha123
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
